### ISSUE TITLE
sixel support

### ISSUE THREAD

**Issue by srlehn** [itchyny/mkrg#2]
In case you need help with the scaling of the sixel graphics you could check out my little project https://github.com/gizak/termui/pull/233.

I use a combination of the ioctl TIOCGWINSZ and the escape codes \033[14t and \033[18t. This can be a bit more difficult with split views of terminal multiplexers like screen and tmux. tmux can pass escape codes through to the terminal.

It is possible to ask the terminal if it is capable to display sixel graphics - the response to \033[0c should contain a 4.

**Comment by itchyny** [comment]
Getting the terminal size in pixel? Sounds great, I'll look into it, thanks.
